#!/bin/sh

set -e

githome=/var/lib/gitlabhq-gitolite

adduser --system                      \
        --shell /bin/sh               \
        --gecos "Git Version Control" \
        --quiet                       \
        --group                       \
        --no-create-home              \
        --disabled-password           \
        --home $githome               \
        git

chown git /var/log/gitlabhq-gitolite
chown git:git $githome

test -d $githome/repositories || {
  mkdir $githome/repositories
  chown git:git $githome/repositories
  chmod ug+rwXs,o-rwx $githome/repositories
}

test -d $githome/.gitolite || {
  mkdir $githome/.gitolite
  ln -s /var/log/gitlabhq-gitolite $githome/.gitolite/logs
  chown -R git:git $githome/.gitolite
  chmod -R 750 $githome/.gitolite
}
