#!/bin/sh

set -e

githome=/var/lib/gitlabhq-gitolite
glhome=/var/lib/gitlabhq

adduser --system               \
        --shell /bin/sh        \
        --gecos "GitLab"       \
        --quiet                \
        --group                \
        --no-create-home       \
        --disabled-login       \
        --home $glhome         \
        gitlab

usermod -G git gitlab

chown gitlab /var/log/gitlabhq
chown gitlab:gitlab $glhome

test -f $glhome/.ssh/id_rsa || {
  ssh-keygen -q -N "" -t rsa -f $glhome/.ssh/id_rsa
  chown -R gitlab:gitlab $glhome/.ssh
  chmod 0700 $glhome/.ssh
  chmod 0400 $glhome/.ssh/id_rsa
  chmod 0444 $glhome/.ssh/id_rsa.pub

  cp $glhome/.ssh/id_rsa.pub $githome/gitlab.pub
  su - -c "gitolite setup -pk $githome/gitlab.pub" git 1>&2
}

test -f $glhome/.gitconfig || {
  su - -c "git config --global user.name GitLab" gitlab
  su - -c "git config --global user.email gitlab@localhost.localdomain" gitlab
}

test -h /var/www/gitlabhq/log || {
  ln -s /var/log/gitlabhq /var/www/gitlabhq/log
}

test -d /var/www/gitlabhq/tmp || {
  mkdir /var/www/gitlabhq/tmp
  chown gitlab:gitlab /var/www/gitlabhq/tmp
}

cp /var/www/gitlabhq/lib/hooks/post-receive $githome/.gitolite/hooks/common/post-receive
chown git:git $githome/.gitolite/hooks/common/post-receive
