#!/bin/sh

set -e

adduser --system                      \
        --shell /bin/sh               \
        --gecos "Git Version Control" \
        --quiet                       \
        --group                       \
        --no-create-home              \
        --disabled-password           \
        --home /var/lib/git           \
        git

test -d /var/lib/git || {
  mkdir /var/lib/git
  chown git:git /var/lib/git
  chmod 0750 /var/lib/git
}

test -d /var/lib/git/repositories || {
  mkdir /var/lib/git/repositories
  chown git:git /var/lib/git/repositories
  chmod ug+rwXs /var/lib/git/repositories
}

test -d /var/lib/git/.gitolite || {
  mkdir /var/lib/git/.gitolite
  mkdir /var/lib/git/.gitolite/logs
  chown -R git:git /var/lib/git/.gitolite
  chmod -R 750 /var/lib/git/.gitolite
}
