#!/bin/sh

set -e

githome=/var/lib/gitlabhq-gitolite

adduser --system               \
        --shell /bin/sh        \
        --gecos "GitLab"       \
        --quiet                \
        --group                \
        --no-create-home       \
        --disabled-login       \
        --home /home/gitlab    \
        gitlab

usermod -G git gitlab

chown gitlab /var/log/gitlabhq

test -d /home/gitlab || {
  mkdir /home/gitlab
  chown gitlab:gitlab /home/gitlab
  chmod 0750 /home/gitlab
}

test -d /home/gitlab/.ssh || {
  mkdir /home/gitlab/.ssh
  ssh-keygen -q -N "" -t rsa -f /home/gitlab/.ssh/id_rsa
  chown -R gitlab:gitlab /home/gitlab/.ssh
  chmod 0700 /home/gitlab/.ssh
  chmod 0400 /home/gitlab/.ssh/id_rsa
  chmod 0444 /home/gitlab/.ssh/id_rsa.pub

  cp /home/gitlab/.ssh/id_rsa.pub $githome/gitlab.pub
  su - -c "gitolite setup -pk $githome/gitlab.pub" git 1>&2
}

test -f /home/gitlab/.ssh/config || {
  echo "Host *"                          >/home/gitlab/.ssh/config
  echo "  StrictHostKeyChecking no"     >>/home/gitlab/.ssh/config
  echo "  UserKnownHostsFile=/dev/null" >>/home/gitlab/.ssh/config

  chown gitlab:gitlab /home/gitlab/.ssh/config
}

test -f /home/gitlab/.gitconfig || {
  su - -c "git config --global user.name GitLab" gitlab
  su - -c "git config --global user.email gitlab@localhost.localdomain" gitlab
}

test -h /var/www/gitlabhq/log || {
  ln -s /var/log/gitlabhq /var/www/gitlabhq/log
}

test -d /var/www/gitlabhq/tmp || {
  mkdir /var/www/gitlabhq/tmp
  chown gitlab:gitlab /var/www/gitlabhq/tmp
}

cp /var/www/gitlabhq/lib/hooks/post-receive $githome/.gitolite/hooks/common/post-receive
chown git:git $githome/.gitolite/hooks/common/post-receive
